apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-cluster-dns
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/eShoshoneDevOps/fleet-charts
    path: network/cluster-dns
    targetRevision: v0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-poc-cluster-dns
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true