apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-cluster-dns
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: ghcr.io/eshoshonedevops
    chart: charts/network/cluster-dns
    targetRevision: 0.2.3
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-poc-cluster-dns
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true