apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-hosted-zone
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: ghcr.io/eshoshonedevops/charts/cloud/aws
    chart: hosted-zone
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-poc-hosted-zone
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true